//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class _Default {

    protected global::System.Web.UI.WebControls.Label FormLabelName;

    protected global::System.Web.UI.WebControls.TextBox FormInputName;

    protected global::System.Web.UI.WebControls.Label FormLabelDate;

    protected global::System.Web.UI.WebControls.TextBox FormInputDate;

    protected global::System.Web.UI.WebControls.Label FormLabelBuild;

    protected global::System.Web.UI.WebControls.DropDownList FormDropBuilding;

    protected global::System.Web.UI.WebControls.Label FormLabelType;

    protected global::System.Web.UI.WebControls.DropDownList FormDropType;

    protected global::System.Web.UI.WebControls.Label FormLabelOther;

    protected global::System.Web.UI.WebControls.TextBox FormInputOther;

    protected global::System.Web.UI.WebControls.Button BtnSaveNode;



    protected global::System.Web.UI.WebControls.DropDownList FilterBuilding;

    protected global::System.Web.UI.WebControls.TextBox FilterName;

    protected global::System.Web.UI.WebControls.DropDownList FilterType;

    protected global::System.Web.UI.WebControls.TextBox FilterDeviceCnt;

    protected global::System.Web.UI.WebControls.TextBox FilterDateFrom;

    protected global::System.Web.UI.WebControls.Label FilterDateTo;



    protected global::System.Web.UI.WebControls.CheckBox GroupByBuilding;

    protected global::System.Web.UI.WebControls.CheckBox GroupByName;

    protected global::System.Web.UI.WebControls.CheckBox GroupByType;

    protected global::System.Web.UI.WebControls.CheckBox GroupByDate;

    protected global::System.Web.UI.WebControls.CheckBox GroupByDevices;

    protected global::System.Web.UI.WebControls.GridView GridCommunication;
    
    protected global::System.Web.UI.WebControls.DropDownList GridDropBuilding;

    protected global::System.Web.UI.WebControls.Label GridLabelBuilding;

    protected global::System.Web.UI.WebControls.DropDownList GridDropType;

    protected global::System.Web.UI.WebControls.Label GridLabelType;

    protected global::System.Web.UI.WebControls.TextBox GridEditName;

    protected global::System.Web.UI.WebControls.Label GridLabelName;

    protected global::System.Web.UI.WebControls.TextBox GridEditOther;

    protected global::System.Web.UI.WebControls.Label GridLabelOther;

    protected global::System.Web.UI.WebControls.TextBox GridEditDate;

    protected global::System.Web.UI.WebControls.Label GridLabelDate;

    protected global::System.Web.UI.WebControls.Button BtnEditSaveCancel;

    protected global::System.Web.UI.WebControls.Button BtnEditDeleteCancel;
    
    protected global::System.Web.UI.WebControls.HiddenField TreeDataHidden;
}