// <auto-generated>//     This code was generated by a tool.// </auto-generated>public partial class equipments {
    // SqlDataSource объ€влени€
    protected global::System.Web.UI.WebControls.SqlDataSource equipmentes;    protected global::System.Web.UI.WebControls.SqlDataSource nodes;    protected global::System.Web.UI.WebControls.SqlDataSource models;    protected global::System.Web.UI.WebControls.SqlDataSource owners;    protected global::System.Web.UI.WebControls.SqlDataSource place;    protected global::System.Web.UI.WebControls.SqlDataSource nodes_type;

    // ‘ильтры и элементы управлени€ фильтрами
    protected global::System.Web.UI.WebControls.Label LabelFilterNode;    protected global::System.Web.UI.WebControls.DropDownList DropDownList4;    protected global::System.Web.UI.WebControls.Label Label11;    protected global::System.Web.UI.WebControls.DropDownList DropDownList5;    protected global::System.Web.UI.WebControls.Label Label12;    protected global::System.Web.UI.WebControls.DropDownList DropDownList6;    protected global::System.Web.UI.WebControls.Label Label13;    protected global::System.Web.UI.WebControls.TextBox TextBox9;    protected global::System.Web.UI.WebControls.Label Label14;    protected global::System.Web.UI.WebControls.TextBox TextBox10;    protected global::System.Web.UI.WebControls.Label Label15;    protected global::System.Web.UI.WebControls.TextBox TextBox11;    protected global::System.Web.UI.WebControls.Label Label16;    protected global::System.Web.UI.WebControls.TextBox TextBox12;

    // —уществующие элементы CheckBox
    protected global::System.Web.UI.WebControls.CheckBox chkColumn1;    protected global::System.Web.UI.WebControls.CheckBox chkColumn2;    protected global::System.Web.UI.WebControls.CheckBox chkColumn3;    protected global::System.Web.UI.WebControls.CheckBox chkColumn4;    protected global::System.Web.UI.WebControls.CheckBox chkColumn5;

    // —уществующие элементы фильтрации
    protected global::System.Web.UI.WebControls.Label LabelFilterBuilding;    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBuilding;    protected global::System.Web.UI.WebControls.Label Label6;    protected global::System.Web.UI.WebControls.TextBox TextBox15;    protected global::System.Web.UI.WebControls.Label LabelFilterType;    protected global::System.Web.UI.WebControls.DropDownList ddlFilterType;    protected global::System.Web.UI.WebControls.Label LabelFilterDevice;    protected global::System.Web.UI.WebControls.DropDownList ddlFilterDevice;

    // LinkButton дл€ добавлени€ оборудовани€
    protected global::System.Web.UI.WebControls.LinkButton LinkButton1;

    //  нопки в GridView
    protected global::System.Web.UI.WebControls.Button Button1;    protected global::System.Web.UI.WebControls.Button Button3;    protected global::System.Web.UI.WebControls.GridView GridView1;

    // Ёлементы управлени€ дл€ модального окна добавлени€ оборудовани€
    protected global::System.Web.UI.WebControls.Label Label1;    protected global::System.Web.UI.WebControls.Label Label2;    protected global::System.Web.UI.WebControls.Label Label3;    protected global::System.Web.UI.WebControls.Label Label4;    protected global::System.Web.UI.WebControls.Label Label5;    protected global::System.Web.UI.WebControls.Label Label8;    protected global::System.Web.UI.WebControls.Label Label9;    protected global::System.Web.UI.WebControls.Label Label10;

    protected global::System.Web.UI.WebControls.DropDownList DropDownList1;    protected global::System.Web.UI.WebControls.DropDownList DropDownList2;    protected global::System.Web.UI.WebControls.DropDownList DropDownList3;

    protected global::System.Web.UI.WebControls.TextBox TextBox1;    protected global::System.Web.UI.WebControls.TextBox TextBox2;    protected global::System.Web.UI.WebControls.TextBox TextBox3;    protected global::System.Web.UI.WebControls.TextBox TextBox4;    protected global::System.Web.UI.WebControls.TextBox TextBox5;    protected global::System.Web.UI.WebControls.TextBox TextBox8;

    protected global::System.Web.UI.WebControls.Button Button2;}